services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor  # Sincroniza la carpeta `vendor/`
    env_file:
      - .env
    networks:
      - laravel

networks:
  laravel:
