services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./aspy:/var/www/aspy
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets
    depends_on:
      - php
      - db
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: aspy-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: aspy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: aspy
    volumes:
      - ./aspy:/var/www/aspy
    working_dir: /var/www/aspy

    networks:
      - laravel

networks:
  laravel:
    name: laravel
    driver: bridge
