name: Deploy frontend to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Remove node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json
        working-directory: ./aspy-web
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --force
        working-directory: ./aspy-web

      - name: Build project
        run: npm run build
        working-directory: ./aspy-web

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './aspy-web/dist'


  deploy:
      permissions:
          contents: read
          pages: write
          id-token: write
      environment:
        name: github-pages
        url: https://aspy-ecuador.github.io/Aspy/
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4