name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend # Rama que dispara el workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del c贸digo
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configuraci贸n de Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'     

    # Paso 5: Instalar las dependencias nuevamente
    - name: Install dependencies
      run: npm install --force

    # Paso 6: Construir la aplicaci贸n
    - name: Build the application
      run: npm run build

    # Paso 7: Desplegar a GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: dist      # La carpeta de salida de tu build
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticaci贸n de GitHub
